spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  liquibase:
    change-log: liquibase/changelog-master.yaml
    default-schema: social_network
  security:
    user:
      name: ${security.admin.name}
      password: ${security.admin.password}
      roles: ${security.admin.roles}
springdoc:
  show-login-endpoint: true


